spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: spring-6-rest-mvc
            uri: http://localhost:8081
            predicates:
              - Path=/api/v1/*

logging:
  level:
    root: error
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: trace
